language:
  - cpp

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - cmake

# TODO: add any dependencies
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - "[ $CXX = g++ ] && export CXX=g++-7 || true"
  - cd ..

script:
  - make
  - make test
